# Server, where virtual machines are installed
server:
  ip-address: 172.16.29.1

# Virtual machines' (vMXs') names and IP addresses
hosts:
  r1: 172.16.29.201
  r2: 172.16.29.202
  r3: 172.16.29.203
  r4: 172.16.29.204
  r5: 172.16.29.205
  vrdevice: 172.16.29.209

# JunOS configs directory
# E.g. if lab configs for lab 9 are located in
# /home/roman/JS-topologies/JNCIE-SP_Bootcamp_12a_L9/configset/
#dir:
  # Note: no trailing "/" please
#  top_dir: /home/roman/JS-topologies
#  subdir_level_1: JNCIE-SP_Bootcamp_12a_L
#  subdir_level_2: configset

# /Users/roman/PycharmProjects/JS-topologies/12a/JNCIE-SP_Bootcamp_12a_TOPOLOGIES_2015_11_10
dir:
  # Note: no trailing "/" please
  top_dir: /Users/roman/PycharmProjects/JS-topologies/12a/JNCIE-SP_Bootcamp_12a_TOPOLOGIES_2015_11_10
  subdir_level_1: JNCIE-SP_Bootcamp_12a_L
  subdir_level_2: configset


# Authentication
auth:
  user: roman
  # password or key?
  method: password
  # set password to False if key authentication used - it will be ignored
  password: junos1
