# Example:
# If lab configs for lab 9 are located in
# /home/roman/JS-topologies/JNCIE-SP_Bootcamp_12a_L9/configset/

# Host names in lower case
# Host names must be resolvable (e.g. via /etc/hosts)
hosts:
  r1: 172.16.29.201
  r2: 172.16.29.202
  r3: 172.16.29.203
  r4: 172.16.29.204
  r5: 172.16.29.205
  vrdevice: 172.16.29.209

dir:
  # no trailing "/"
  top_dir: /home/roman/JS-topologies
  subdir_level_1: JNCIE-SP_Bootcamp_12a_L
  subdir_level_2: configset

auth:
  user: roman
  # password or ssh?
  method: 5
  # set password to False if ssh authentication used - it will be ignored
  password: junos1

# Choose library (PyEz or NAPALM) to push config
driver: junos
